theme: minima
title: github_page_test
author: tim.liang 
email: tim.liang@advantech.com.tw
description: > # this means to ignore newlines until "baseurl:"
  this is the first time to Microsoft.
  I'm taking a github class.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
